// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Testcase struct {
	ID           int64   `json:"id"`
	Classname    string  `json:"classname"`
	Filename     string  `json:"filename"`
	Linenumber   int32   `json:"linenumber"`
	Testcasename string  `json:"testcasename"`
	Duration     float64 `json:"duration"`
	Username     string  `json:"username"`
}

type User struct {
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	Email          string    `json:"email"`
	CreatedOn      time.Time `json:"created_on"`
}
