// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Testcase struct {
	ID           int64   `json:"id"`
	Classname    string  `json:"classname"`
	Filename     string  `json:"filename"`
	Linenumber   int32   `json:"linenumber"`
	Testcasename string  `json:"testcasename"`
	Duration     float64 `json:"duration"`
}
